name: CI Pipeline

on:
  pull_request:
    branches:
      - feat/pipeline
  push:
    branches:
      - feat/pipeline
#Detailed jobs for the pipeline to do
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov  # Install testing dependencies

      - name: Run Unit Tests
        run: |
          pytest

      - name: Generate Code Coverage
        run: |
          pytest --cov=tests/
  test:
    steps:
      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
          sudo apt-get install -y --no-install-recommends ffmpeg
          pip install pytest-cov
          python -m pip install coverage

      - name: Instalar dependencias necesarias
        run: |
          sudo apt-get install -y --no-install-recommends \
            libgl1-mesa-glx \
            libglib2.0-0 \
            ffmpeg 
      - name: verificar que tiene acceso a las imagenes
      run: |
        ls -la tests/routes
             
      - name: Run unit tests and check code coverage
      run: |
        coverage run -m unittest
        coverage report -m
