name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
#Detailed jobs for the pipeline to dos
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          sudo apt-get install -y --no-install-recommends libgl1-mesa-glx libglib2.0-0 ffmpeg perl
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov  # Install testing dependencies

      - name: Run Unit Tests
        run: |
          pytest

      - name: Generate Code Coverage
        run: |
          pytest --cov=tests/ --cov-report xml:coverage.xml

  static-code-analysis:
    needs: build
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Static Code Analysis with SonarQube
      uses: sonarsource/sonarqube-scan-action@v4.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=ConverterService
          -Dsonar.python.coverage.reportPaths=coverage.xml
    
    - name: SonarQube Quality Gate check
      uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
